#pragma once

#define PRODUCT_VERSION_STRING "2024 version 2.26"
#define VER_MAJOR	2024
#define VER_MINOR	2
#define VER_REV		26
#define VER_BUILD	170

#define TOSTRING(x) #x
#define VERSION_STRING	TOSTRING(VER_MAJOR) "." TOSTRING(VER_MINOR) "." TOSTRING(VER_REV) "." TOSTRING(VER_BUILD)
